### ISSUE TITLE
unit test for image 14 and jhove

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#2]
definition of jhove stuff is at jhoveMetadataExtractor.xml

Good luck,
Jan Stavel

**Comment by jonatansve** [comment]
I receive an exception when I transform the raw jhove file. 

[Fatal Error] :3:1: Premature end of file.
org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 1; Premature end of file.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:253)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:288)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at cz.nkp.differ.compare.metadata.external.XSLTTransformer.transform(XSLTTransformer.java:57)

The input to the transformer is simply the xml file
https://github.com/Differ-GSOC/differ/blob/master/docs/examples/images_01/14/output-jhove.raw

I have removed the first line with READBOX seen=true, but to no success.

Any ideas why it could be failing to parse it?

**Comment by jstavel** [comment]
Hi Jonathan, try to call differ-cmdline application on a given image. Outputs will be stored at new directory without result.

I hope you will get output that goes well.

Regards,
Jan Stavel
