### ISSUE TITLE
Results not showing for different formats

### ISSUE THREAD

**Issue by xrosecky** [Differ-GSOC/differ#31]
Results are not shown when formats on images differ - for example JPEG or PNG. It throws:

Sep 17, 2013 7:25:11 PM com.vaadin.Application terminalError
SEVERE: Terminal error:
java.lang.IndexOutOfBoundsException: Index: 124, Size: 117
        at java.util.ArrayList.RangeCheck(ArrayList.java:547)
        at java.util.ArrayList.get(ArrayList.java:322)
        at cz.nkp.differ.compare.io.generators.ImageMetadataComponentGenerator$2.getStyle(ImageMetadataComponentGenerator.java:236)
        at com.vaadin.ui.Table.paintRowAttributes(Table.java:3410)
        at com.vaadin.ui.Table.paintRow(Table.java:3306)
        at com.vaadin.ui.Table.paintRows(Table.java:3152)
        at com.vaadin.ui.Table.paintContent(Table.java:2764)

**Comment by xanat0s** [comment]
Resolved: https://github.com/Differ-GSOC/differ/commit/8abbabae0f087225e5d2a03aad03aa205f591549

**Comment by xanat0s** [comment]
Vasek I'll let you review it before closing it.

**Comment by xrosecky** [comment]
Fixed in current version.
